### ISSUE TITLE
🐛 IncRunCountFromFileName error

### ISSUE THREAD

**Issue by neo-fan** [lin-ycv/EverythingPowerToys#108]
版本信息: powerToys:0.81.0 插件:0.81.0
# 使用插件搜索后 点击搜索结果中任意一条，可正常执行，但是报错

![image](https://github.com/lin-ycv/EverythingPowerToys/assets/29839040/ef27071e-81f5-451f-b72d-7c75d5181b3f)

简单查了一下应该 好像是使用了错误的方法名 Everything64.dll
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/29839040/ffcf2cb9-f074-4515-a963-33c971451008)

**Comment by neo-fan** [comment]
版本信息 ： powertoys:

**Comment by lin-ycv** [comment]
請問你是x64還是arm?

**Comment by neo-fan** [comment]
> 請問你是x64還是arm?

x64

**Comment by kai-earthrise** [comment]
I'm also on x64 and am seeing an identical error.

**Comment by lin-ycv** [comment]
外掛0.80.0版本也會嗎，還是只有新版的81才會？
看來是我改用LibraryImport的問題

**Comment by kai-earthrise** [comment]
Yep, version 0.80.0 does not throw the error.

**Comment by Hungnth** [comment]
I also got the same error when opening the file from powerstoys run (powertoys 0.81)

Version: 0.81.0.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True
Date: 05/23/2024 10:40:02
Exception:
System.EntryPointNotFoundException: Unable to find an entry point named 'Everything_IncRunCountFromFileName' in DLL 'Everything64.dll'.
   at Community.PowerToys.Run.Plugin.Everything.Interop.NativeMethods.<Everything_IncRunCountFromFileName>g____PInvoke|7_0(UInt16* __lpFileName_native)
   at Community.PowerToys.Run.Plugin.Everything.Interop.NativeMethods.Everything_IncRunCountFromFileName(String lpFileName)
   at Community.PowerToys.Run.Plugin.Everything.Everything.<>c__DisplayClass2_0.<Query>b__0(ActionContext e)
   at PowerLauncher.ViewModel.MainViewModel.<>c__DisplayClass31_0.<OpenResultsEvent>b__0()
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at PowerLauncher.ViewModel.MainViewModel.OpenResultsEvent(Object index, Boolean isMouseClick)
   at PowerLauncher.ViewModel.MainViewModel.<InitializeKeyCommands>b__32_11(Object index)
   at PowerLauncher.ViewModel.RelayCommand.Execute(Object parameter)
   at PowerLauncher.MainWindow.SuggestionsList_PreviewMouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lin-ycv** [comment]
Issue identified, WIP, will push a fix soon.
