### ISSUE TITLE
🐛 New ARM version can't Load

### ISSUE THREAD

**Issue by dXrayb** [lin-ycv/EverythingPowerToys#112]
**Flight Check**
- [x] I'm sure existing (open and closed) don't have duplicates
- [x] I've tried reinstalling PT, Everything, EverythingPT

**Describe the bug**
The new ARM version can't load correctly.

**To Reproduce**
Download new version package and extract to %LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins folder, restart PowerToys.

**Screenshots**
---------------------------
PowerToys Run - Plugin Loading Error
---------------------------
Fail to load plugin: Everything

Please report the bug to https://aka.ms/powerToysReportBug. (For third-party plugins, please contact the plugin author.)
---------------------------
确定   
---------------------------

**Logs (please upload or provide link to you log):**
[2024-05-28 11:44:01.6645] [INFO] [C:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::55]
Starting PowerToys Run with PID=3548

[2024-05-28 11:44:01.7958] [INFO] [C:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::66]
Runner pid=19972

[2024-05-28 11:44:03.7878] [INFO] [C:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::108]
On Startup.

[2024-05-28 11:44:04.2221] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
ImageLoader.Initialize - Preload images cost <9ms>

[2024-05-28 11:44:04.2221] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Image\ImageLoader.cs::99]
Number of preload images is <116>, Images Number: 2, Unique Items 2

[2024-05-28 11:44:04.7209] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
|Wox.Infrastructure.Alphabet.Initialize|Preload pinyin cache <441ms>

[2024-05-28 11:44:04.7209] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Alphabet.cs::46]
Number of preload pinyin combination<0>

[2024-05-28 11:44:04.9289] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Calculator> is <4ms>

[2024-05-28 11:44:05.0703] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::169]
-------------------------- Begin exception --------------------------
Message: Couldn't load assembly for Everything in C:\Program Files\PowerToys\RunPlugins\Everything\Community.PowerToys.Run.Plugin.Everything.dll

Exception full name  : System.IO.FileLoadException
Exception message    : Could not load file or assembly 'Community.PowerToys.Run.Plugin.Everything, Version=0.81.0.1, Culture=neutral, PublicKeyToken=null'.
Exception stack trace:
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Wox.Plugin.PluginPair.CreatePluginInstance()
Exception source     : System.Private.CoreLib
Exception target site: System.Reflection.Assembly LoadFromAssemblyPath(System.String)
Exception HResult    : -2146232799
-------------------------- End exception --------------------------

[2024-05-28 11:44:05.0703] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Everything> is <137ms>

[2024-05-28 11:44:05.0850] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Folder> is <3ms>

[2024-05-28 11:44:05.0955] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <History> is <1ms>

[2024-05-28 11:44:05.0955] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Indexer> is <2ms>

[2024-05-28 11:44:05.1155] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <OneNote> is <1ms>

[2024-05-28 11:44:05.1265] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <PowerToys> is <3ms>

[2024-05-28 11:44:05.3004] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Program> is <165ms>

[2024-05-28 11:44:05.3172] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Registry> is <1ms>

[2024-05-28 11:44:05.4662] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Service> is <140ms>

[2024-05-28 11:44:05.4891] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Shell> is <13ms>

[2024-05-28 11:44:05.5389] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <System Commands> is <40ms>

[2024-05-28 11:44:05.5536] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Time and date> is <2ms>

[2024-05-28 11:44:05.5649] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Unit Converter> is <1ms>

[2024-05-28 11:44:05.5796] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Uri Handler> is <3ms>

[2024-05-28 11:44:05.5907] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <ValueGenerator> is <2ms>

[2024-05-28 11:44:05.6834] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <VS Code Workspaces> is <83ms>

[2024-05-28 11:44:05.6943] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Web Search> is <1ms>

[2024-05-28 11:44:05.7041] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Settings> is <1ms>

[2024-05-28 11:44:05.7355] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Terminal> is <22ms>

[2024-05-28 11:44:05.7487] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Window Walker> is <1ms>

[2024-05-28 11:44:06.4314] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Image\WindowsThumbnailProvider.cs::119]
Error while creating item. retCode:-2147024891 

[2024-05-28 11:44:06.4314] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Image\WindowsThumbnailProvider.cs::146]
-------------------------- Begin exception --------------------------
Message: Error while extracting thumbnail for C:\ProgramData\Microsoft\NetFramework\BreadcrumbStore\netcore,LibGit2Sharp,0.27.0-preview-0182

Exception full name  : System.UnauthorizedAccessException
Exception message    : 拒绝访问。 (0x80070005 (E_ACCESSDENIED))
Exception stack trace:
   at Wox.Infrastructure.Image.WindowsThumbnailProvider.GetHBitmap(String fileName, Int32 width, Int32 height, ThumbnailOptions options)
Exception source     : Wox.Infrastructure
Exception target site: IntPtr GetHBitmap(System.String, Int32, Int32, Wox.Infrastructure.Image.ThumbnailOptions)
Exception HResult    : -2147024891
-------------------------- End exception --------------------------

[2024-05-28 11:44:06.4348] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Image\ImageLoader.cs::172]
-------------------------- Begin exception --------------------------
Message: Failed to get thumbnail for C:\ProgramData\Microsoft\NetFramework\BreadcrumbStore\netcore,LibGit2Sharp,0.27.0-preview-0182

Exception full name  : System.UnauthorizedAccessException
Exception message    : 拒绝访问。 (0x80070005 (E_ACCESSDENIED))
Exception stack trace:
   at Wox.Infrastructure.Image.WindowsThumbnailProvider.GetHBitmap(String fileName, Int32 width, Int32 height, ThumbnailOptions options)
   at Wox.Infrastructure.Image.WindowsThumbnailProvider.GetThumbnail(String fileName, Int32 width, Int32 height, ThumbnailOptions options)
   at Wox.Infrastructure.Image.ImageLoader.GetThumbnailResult(String& path, Boolean generateThumbnailsFromFiles, Boolean loadFullImage)
   at Wox.Infrastructure.Image.ImageLoader.<>c__DisplayClass18_0.<LoadInternalAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Wox.Infrastructure.Image.ImageLoader.LoadInternalAsync(String path, Boolean generateThumbnailsFromFiles, Boolean loadFullImage)
Exception source     : Wox.Infrastructure
Exception target site: IntPtr GetHBitmap(System.String, Int32, Int32, Wox.Infrastructure.Image.ThumbnailOptions)
Exception HResult    : -2147024891
-------------------------- End exception --------------------------

[2024-05-28 11:44:07.2667] [INFO] [C:\a\_work\1\s\src\modules\launcher\PowerLauncher\SettingsReader.cs::87]
Successfully read new settings. retryCount=1

[2024-05-28 11:44:07.2811] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\xray\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Shell\ShellPluginSettings.json>

[2024-05-28 11:44:07.4182] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Registry> is <2ms>

[2024-05-28 11:44:07.4182] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Shell> is <15ms>

[2024-05-28 11:44:07.4182] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <ValueGenerator> is <4ms>

[2024-05-28 11:44:07.4182] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Calculator> is <6ms>

[2024-05-28 11:44:07.4182] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Time and date> is <4ms>

[2024-05-28 11:44:07.4182] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <System Commands> is <41ms>

[2024-05-28 11:44:07.4182] [WARN] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::225]
Can not initialize Everything plugin as it was not loaded

[2024-05-28 11:44:07.4182] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Unit Converter> is <1ms>

[2024-05-28 11:44:07.4182] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <History> is <1ms>

[2024-05-28 11:44:07.4182] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Window Walker> is <2ms>

[2024-05-28 11:44:07.4182] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Service> is <144ms>

[2024-05-28 11:44:07.4182] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Folder> is <10ms>

[2024-05-28 11:44:07.4493] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Windows Settings> is <30ms>

**Version:**
 - PowerToy: v0.81.0
 - Everything: V1.4.1.1023 (ARM) 
 - EverythingPT: [v0.81.0.1](https://github.com/lin-ycv/EverythingPowerToys/releases/tag/v0.81.0.1) 
 - Windows:22631.3593

 **Installation method (How did you install the following softwares):**
 - PowerToys: Github
 - Everything:Official Build
 - EverythingPT:Github

**Comment by lin-ycv** [comment]
Do you have multiple versions of EPT installed? Why does it say
`Couldn't load assembly for Everything in C:\Program Files\PowerToys\RunPlugins\Everything\Community.PowerToys.Run.Plugin.Everything.dll`, it says the plugin is installed in program files instead of the appdata folder? 

Does anything in #45 solve your issue?

**Comment by lin-ycv** [comment]
few things to try
1. try a previous version and replace with ARM dll
2. try the ARM Update 1 dll from [voidtools forum](https://www.voidtools.com/forum/viewtopic.php?p=57654#p57654)
3. try installing EPT to `C:\Program Files\PowerToys\RunPlugins\Everything\` instead

see if any of these solves the issue

**Comment by dXrayb** [comment]
> few things to try
> 
> 1. try a previous version and replace with ARM dll
> 2. try the ARM Update 1 dll from [voidtools forum](https://www.voidtools.com/forum/viewtopic.php?p=57654#p57654)
> 3. try installing EPT to `C:\Program Files\PowerToys\RunPlugins\Everything\` instead
> 
> see if any of these solves the issue

1. previous version work well
2. The effect of two DLL files is the same. I am the author of this post. 
3. At the beginning, I extracted and overwrote them in this directory, but later there was an error. I reinstalled using the installation package and deleted the original files, but it still didn't work.

**Comment by lin-ycv** [comment]
@dXrayb Please try these 3 and see if any of them work. Completely remove any previous installs of EPT, no need to change or swap out dll, test the zip packages as is.
[EverythingPT-0.81.0.1-ARM64_NoCheck.zip](https://github.com/user-attachments/files/15508261/EverythingPT-0.81.0.1-ARM64_NoCheck.zip)
[EverythingPT-0.81.0.1-ARM64_NoCheckNoLib.zip](https://github.com/user-attachments/files/15508262/EverythingPT-0.81.0.1-ARM64_NoCheckNoLib.zip)
[EverythingPT-0.81.0.1-x64+ARM64_NoLib.zip](https://github.com/user-attachments/files/15508263/EverythingPT-0.81.0.1-x64%2BARM64_NoLib.zip)

**Comment by dXrayb** [comment]
> @dXrayb Please try these 3 and see if any of them work. Completely remove any previous installs of EPT, no need to change or swap out dll, test the zip packages as is. [EverythingPT-0.81.0.1-ARM64_NoCheck.zip](https://github.com/user-attachments/files/15508261/EverythingPT-0.81.0.1-ARM64_NoCheck.zip) [EverythingPT-0.81.0.1-ARM64_NoCheckNoLib.zip](https://github.com/user-attachments/files/15508262/EverythingPT-0.81.0.1-ARM64_NoCheckNoLib.zip) [EverythingPT-0.81.0.1-x64+ARM64_NoLib.zip](https://github.com/user-attachments/files/15508263/EverythingPT-0.81.0.1-x64%2BARM64_NoLib.zip)

Okay, It didn't work too, and the logs are here. The newest function version is 0.80.

[EverythingPT-0.81.0.1-ARM64_NoCheck.txt](https://github.com/user-attachments/files/15508989/EverythingPT-0.81.0.1-ARM64_NoCheck.txt)
[EverythingPT-0.81.0.1-ARM64_NoCheckNoLib.txt](https://github.com/user-attachments/files/15508991/EverythingPT-0.81.0.1-ARM64_NoCheckNoLib.txt)
[EverythingPT-0.81.0.1-x64+ARM64_NoLib.txt](https://github.com/user-attachments/files/15508995/EverythingPT-0.81.0.1-x64%2BARM64_NoLib.txt)

**Comment by lin-ycv** [comment]
this makes no sense, because NoLib is basically 0.80.0 with very few minor changes.
The 2 logs you provided doesn't offer any insights either, it just says theplugin is not loaded, but there's no errors or excepts.
Maybe we can wait for other ARM users to chime in.

**Comment by dXrayb** [comment]
> this makes no sense, because NoLib is basically 0.80.0 with very few minor changes. The 3 logs you provided doesn't offer any insights either, it just says the plugin is not loaded, but there's no errors or exceptions. Maybe we can wait for other ARM users to chime in.

I speculate that the issue might be due to the program being compatible with both x64 and ARM64 architectures. There seems to be a problem when determining the two DLL files. Since I am using ARM64 versions of PowerToys and Everything, the old version works fine by replacing the DLL files, but the new version does not.

**Comment by lin-ycv** [comment]
can you test this version?
[EverythingPT-0.81.1-ARM64.zip](https://github.com/user-attachments/files/16039383/EverythingPT-0.81.1-ARM64.zip)

**Comment by dXrayb** [comment]
> can you test this version? [EverythingPT-0.81.1-ARM64.zip](https://github.com/user-attachments/files/16039383/EverythingPT-0.81.1-ARM64.zip)

It works well.
