### ISSUE TITLE
Everything becomes slow and sometimes no response when working with Powertoys

### ISSUE THREAD

**Issue by DittoWii** [lin-ycv/EverythingPowerToys#137]
I installed EverythinPT 0.85.1, with Everything version 1.5a, Powertoys version 0.85.1.  Everything is installed in the default path, with alpha disabled. 
They work well in the beginning, but when I search more frequently, Everything becomes slow and sometimes no response. But using Everything solely is fine. 
Sometimes the search results are already returned by Everything, but PowerToys is still no response. 
I am glad to provide more info if necessary.

**Comment by lin-ycv** [comment]
Please provide logs.

**Comment by lin-ycv** [comment]
Logs can be generated by right clicking the taskbar icon > Report Bug or be found at %localappdata%\Microsoft\PowerToys\PowerToys Run\Logs

**Comment by DittoWii** [comment]
[PowerToysReport_2024-10-25-10-15-23.zip](https://github.com/user-attachments/files/17514780/PowerToysReport_2024-10-25-10-15-23.zip)
Here is the log files. 
Thanks a lot!

**Comment by c0nstexpr** [comment]
> [PowerToysReport_2024-10-25-10-15-23.zip](https://github.com/user-attachments/files/17514780/PowerToysReport_2024-10-25-10-15-23.zip) Here is the log files. Thanks a lot!

你的log含有个人信息，你得注意一下 @DittoWii 
我能看到的报错信息在这部分

<blockquote>
Exception full name  : System.ArgumentNullException
Exception message    : Value cannot be null. (Parameter 'path1')
Exception stack trace:
   at System.ArgumentNullException.Throw(String paramName)
   at Community.PowerToys.Run.Plugin.Everything.Everything.Query(String query, Settings setting)+MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Community.PowerToys.Run.Plugin.Everything.Main.Query(Query query, Boolean delayedExecution)
Exception source     : System.Private.CoreLib
Exception target site: Void Throw(System.String)
Exception HResult    : -2147467261
-------------------------- End exception --------------------------


[2024-10-24 11:37:05.0691] [WARN] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::230]
PluginManager.QueryForPlugin Everything. Query cost - 1483 milliseconds

[2024-10-24 11:37:05.1422] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Image\WindowsThumbnailProvider.cs::147]
-------------------------- Begin exception --------------------------
Message: Error while extracting thumbnail for C:\Users\DittoWii\OneDrive\...\***.png

Exception full name  : System.Runtime.InteropServices.COMException
Exception message    : 0x8004B205
Exception stack trace:
   at Wox.Infrastructure.Image.WindowsThumbnailProvider.GetHBitmap(String fileName, Int32 width, Int32 height, ThumbnailOptions options)
Exception source     : Wox.Infrastructure
Exception target site: IntPtr GetHBitmap(System.String, Int32, Int32, Wox.Infrastructure.Image.ThumbnailOptions)
Exception HResult    : -2147175931
-------------------------- End exception --------------------------

<blockquote/>

**Comment by DittoWii** [comment]
@c0nstexpr 十分感谢！我已经删除了评论。但是log文件还可以通过您的quote访问到。如果您方便的话麻烦修改下评论。感谢！

**Comment by lin-ycv** [comment]
turn off preview, it's trying to download the thumbnail, but there seems to be dome issues with it, so it's hanging.
將preview功能關掉，雲端檔案讀取預覽有時會有些問題
https://github.com/lin-ycv/EverythingPowerToys/wiki/Features#preview

**Comment by DittoWii** [comment]
> turn off preview, it's trying to download the thumbnail, but there seems to be dome issues with it, so it's hanging. 將preview功能關掉，雲端檔案讀取預覽有時會有些問題 https://github.com/lin-ycv/EverythingPowerToys/wiki/Features#preview

感谢！
我尝试关掉了Preview功能，然后发现了如下错误：
[2024-10-26 10:21:28.0003] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\ShellLinkHelper.cs::170]
-------------------------- Begin exception --------------------------
Message: Failed to fetch description for C:\WINDOWS\syswow64\odbcad32.exe, Error HRESULT E_FAIL has been returned from a call to a COM component.

Exception full name  : System.Runtime.InteropServices.COMException
Exception message    : Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception stack trace:
   at Wox.Infrastructure.ShellLinkHelper.IShellLinkW.GetDescription(StringBuilder pszName, Int32 cchMaxName)
   at Wox.Infrastructure.ShellLinkHelper.RetrieveTargetPath(String path)
Exception source     : Wox.Infrastructure
Exception target site: Void GetDescription(System.Text.StringBuilder, Int32)
Exception HResult    : -2147467259
-------------------------- End exception --------------------------

**Comment by lin-ycv** [comment]
so the issue is here:
https://github.com/lin-ycv/EverythingPowerToys/blob/744be805fb02b4fb34101f051c4ce739442c6e1e/Everything.cs#L135-L137
for some reason the path is null?
do you know which file and location is throwing this error?
are there some specical characters in the file path or something?

**Comment by DittoWii** [comment]
Thanks a lot! 
after tests, no specific paths will lead to this error.
generally, the initial two or three searches return results successfully. 
i will do more tests latter to find the potential reasons...

**Comment by lin-ycv** [comment]
please try v0.86.0
not sure if the issue is fix, but if you still encounter the issue, the log file in `%localappdata%\Microsoft\PowerToys\PowerToys Run\Logs\0.86.0.0` will now log which file is the issue as a warning `[WARN]` in the format:
`Result {i} is null for {name} and/or {path}, query: {query}`
once we know which filename or filepath is the issue, we can do further investigation

**Comment by DittoWii** [comment]
Thanks for your reply! 
But I still encounter this issue. And it seems the `[WANR]` in the logfile cannot always provide the detail...
For example, `name` and `path` is often empty:
`
[2024-11-12 09:57:03.3957] [WARN] [D:\Repo\PowerToys\src\modules\launcher\Plugins\EverythingPowerToys\Everything.cs::142]
Result 8 is null for  and/or , query: Instal

[2024-11-12 09:57:03.3957] [WARN] [D:\Repo\PowerToys\src\modules\launcher\Plugins\EverythingPowerToys\Everything.cs::142]
Result 9 is null for  and/or , query: Instal

[2024-11-12 09:57:03.3957] [WARN] [D:\Repo\PowerToys\src\modules\launcher\Plugins\EverythingPowerToys\Everything.cs::142]
Result 7 is null for  and/or , query: In

[2024-11-12 09:57:03.3957] [WARN] [D:\Repo\PowerToys\src\modules\launcher\Plugins\EverythingPowerToys\Everything.cs::142]
Result 8 is null for  and/or , query: In

[2024-11-12 09:57:03.3957] [WARN] [D:\Repo\PowerToys\src\modules\launcher\Plugins\EverythingPowerToys\Everything.cs::142]
Result 6 is null for  and/or , query: Insta

[2024-11-12 09:57:03.3957] [WARN] [D:\Repo\PowerToys\src\modules\launcher\Plugins\EverythingPowerToys\Everything.cs::142]
Result 7 is null for  and/or , query: Insta

[2024-11-12 09:57:03.3957] [WARN] [D:\Repo\PowerToys\src\modules\launcher\Plugins\EverythingPowerToys\Everything.cs::142]
Result 7 is null for  and/or , query: Installing

[2024-11-12 09:57:03.3957] [WARN] [D:\Repo\PowerToys\src\modules\launcher\Plugins\EverythingPowerToys\Everything.cs::142]
Result 8 is null for  and/or , query: Installing

[2024-11-12 09:58:59.6181] [WARN] [D:\Repo\PowerToys\src\modules\launcher\Plugins\EverythingPowerToys\Everything.cs::142]
Result 0 is null for {076e0629-47ca-4e69-9580-f36bc02b19c5} and/or , query: ca

`
Besides, the occurrence of `WARN` messages and the crash of the search are not always directly correlated. A successful search may entail `WARN` messages, and when the search crashes, there may be no `WARN`s in logfile....
I also found that queries containing Chinese characters generally return results as expected, but after a english query, the search engine appears to crash.

**Comment by lin-ycv** [comment]
Ok, so assuming your sort method in EPT and everything is set to the same.
 
Search for `Instal` in Everything main window, what is the 8th and 9th result?(Starting counting at 0) 

And the last result in your log is interesting 
`Result 0 is null for {076e0629-47ca-4e69-9580-f36bc02b19c5} and/or , query: ca`
When you search `ca` in everything what is the first result? 
`{076e0629-47ca-4e69-9580-f36bc02b19c5}` seems like a guide, is it a mstore app? 

The WRN message is for when null happens and EPT did not show that specific result. 
If you're still encountering crashes, there something else that wrong. But let's deal with the null issue first.

**Comment by DittoWii** [comment]
I think I may have figured out what's wrong...
I set the different sorting method in EPT and everything........  I changed it, problem solved....
Thanks so much for your help!

**Comment by lin-ycv** [comment]
that's weird, the two settings shouldn't conflict...
since it's solved, i'll close the issue, reopen this if it occurs again.
