### ISSUE TITLE
🐛 xx

### ISSUE THREAD

**Issue by SYAx3VTuber** [lin-ycv/EverythingPowerToys#139]
**Flight Check**
- [ ] I'm sure existing (open and closed) don't have duplicates
- [ ] I've tried reinstalling PT, Everything, EverythingPT
[PowerToysReport_2024-11-11-18-33-57.zip](https://github.com/user-attachments/files/17700274/PowerToysReport_2024-11-11-18-33-57.zip)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs (please upload or provide link to you log):**
 Logs can be generated by right clicking the taskbar icon > Report Bug
or be found at
%localappdata%\Microsoft\PowerToys\PowerToys Run\Logs

**Version:**
 - PowerToy:
 - Everything:
 - EverythingPT: 
 - Windows:

 **Installation method (How did you install the following softwares):**
 - PowerToys: Github/Windows Store/Winget..etc
 - Everything:
 - EverythingPT:

**Additional context**

**Comment by lin-ycv** [comment]
First, something's wrong with your PowerToys, you should try to reinstall it first.
```
[2024-11-11 18:32:32.524392] [p-18408] [t-17692] [trace] Register hotkey action for PowerToys Run
[2024-11-11 18:32:32.525517] [p-18408] [t-17692] [error] get_power_toys_settings(): got malformed json for CmdNotFound module
[2024-11-11 18:32:32.525570] [p-18408] [t-17692] [error] get_power_toys_settings(): got malformed json for EnvironmentVariables module
[2024-11-11 18:32:32.525577] [p-18408] [t-17692] [error] get_power_toys_settings(): got malformed json for FancyZones module
[2024-11-11 18:32:32.529363] [p-18408] [t-17692] [error] get_power_toys_settings(): got malformed json for Hosts module
[2024-11-11 18:32:32.529520] [p-18408] [t-17692] [error] get_power_toys_settings(): got malformed json for NewPlus module
[2024-11-11 18:32:32.529761] [p-18408] [t-17692] [error] get_power_toys_settings(): got malformed json for Video Conference module
```

Second, you're on 0.82.1, update to the newest version. Make sure you're on the correct version, either arm or x64, if you not which one you are, try both.
```
-------------------------- Begin exception --------------------------
Message: Couldn't load assembly for Everything in C:\Users\SYAx3_ai\AppData\Local\Microsoft\PowerToys\PowerToys Run\Plugins\Everything\Community.PowerToys.Run.Plugin.Everything.dll

Exception full name  : System.IO.FileLoadException
Exception message    : Could not load file or assembly 'Community.PowerToys.Run.Plugin.Everything, Version=0.82.1.0, Culture=neutral, PublicKeyToken=null'.
Exception stack trace:
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Wox.Plugin.PluginPair.CreatePluginInstance()
Exception source     : System.Private.CoreLib
Exception target site: System.Reflection.Assembly LoadFromAssemblyPath(System.String)
Exception HResult    : -2146232799
-------------------------- End exception --------------------------
```
