### ISSUE TITLE
[BUG] PowerToys crashes when trying to open a folder

### ISSUE THREAD

**Issue by CEbbinghaus** [lin-ycv/EverythingPowerToys#15]
**Describe the bug**
When searching for a file. Clicking on the Directory Icon causes a crash of Power Toys

**To Reproduce**
* Open Power Toys
* Search for Files with Everything Plugin Prefix
* Click on Open Containing Folder icon

**Expected behavior**
Opens a Windows Explorer window with the folder the file is contained in

**Screenshots**
<img width="536" alt="image" src="https://user-images.githubusercontent.com/31423391/168732783-64515d3c-a167-42fa-8e6d-2e0169af0f15.png">

**Logs (please upload or provide link to you log):**
Error:
```
Version: 0.58.0.0
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True
Date: 17/05/2022 2:57:02 PM
Exception:
System.MissingMethodException: Method not found: 'Boolean Wox.Infrastructure.Helper.OpenInShell(System.String, System.String, System.String, Boolean)'.
   at Community.PowerToys.Run.Plugin.Everything.ContextMenuLoader.<>c__DisplayClass6_0.<CreateOpenContainingFolderResult>b__0(ActionContext _)
   at PowerLauncher.ViewModel.ResultViewModel.<>c__DisplayClass32_0.<LoadContextMenu>b__0(Object _)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
[Full Log](https://github.com/lin-ycv/EverythingPowerToys/files/8705287/2022-05-17.txt)

**Version (please provide the version of software you are using):**
 - PowerToy: 0.58.0.0
 - Everything: 1.4.1.1015 (x64)
 - Windows: Windows 11 Pro 22000.493

**Comment by lin-ycv** [comment]
this is the same issues as #9, which is fixed in 0.56.2R2 and above, please update to the [latest version](https://github.com/lin-ycv/EverythingPowerToys/releases/latest).
your log says you're on version 0.55.1
`TargetAssembly: Community.PowerToys.Run.Plugin.Everything, Version=0.55.1.0, Culture=neutral, PublicKeyToken=null`

If the latest version still give you errors, please reopen this issue and let me know.

**Comment by CEbbinghaus** [comment]
Thanks. Didn't realize there was an update

**Comment by CEbbinghaus** [comment]
Thanks yeah that solved the problem
