### ISSUE TITLE
PowerToys Run - Plugin Loading error

### ISSUE THREAD

**Issue by FearlessSong** [lin-ycv/EverythingPowerToys#150]
After update to the latest release, i can not use the PT everything plugin. I have try to reinstall the PT and the plugin, which not work.

**Screenshots**
![bug](https://github.com/user-attachments/assets/b69964e0-cb16-438f-81cf-9c1a4b9ff8f1)

**Comment by FearlessSong** [comment]
![image](https://github.com/user-attachments/assets/806085a9-576c-4bf4-8a05-df6647265236)

**Comment by FearlessSong** [comment]
And i try to degrade the plugin, it works.!!!!!

**Comment by m-nikitin** [comment]
same issue

**Comment by JingshanDu** [comment]
Same here. It seems that the plugin dll has problems being loaded. Consistent behavior on every attempt to load this plugin. Relevant PowerToys Run log excerpts:

```
[2024-12-18 21:53:53.6348] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::181]
-------------------------- Begin exception --------------------------
Message: Couldn't get assembly types for Everything in C:\Users\[USERNAME]\AppData\Local\Microsoft\PowerToys\PowerToys Run\Plugins\Everything\Community.PowerToys.Run.Plugin.Everything.dll. The plugin might be corrupted. Uninstall PowerToys, manually delete the install folder and reinstall.

Exception full name  : System.Reflection.ReflectionTypeLoadException
Exception message    : Unable to load one or more of the requested types.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Exception stack trace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Wox.Plugin.PluginPair.CreatePluginInstance()
Exception source     : System.Private.CoreLib
Exception target site: System.RuntimeType[] GetTypes(System.Reflection.RuntimeModule)
Exception HResult    : -2146232830
-------------------------- End exception --------------------------
```

**Comment by MoshiurRahmanAdib** [comment]
Same problem after the latest update

**Comment by xzy-nine** [comment]
me too

**Comment by lin-ycv** [comment]
@FearlessSong it's because you're on an older version of powertoys
PT uses .NET 8 from v0.76.0 to up until v0.86.0, on v0.87.0 PT switched to .NET 9.
EPT versions are built against the corresponding PT version, so EPT v0.87.0 also targets .NET 9.
if you update your PT first, that'll solve the issue.

@JingshanDu I'm guessing you're also on an older version of PT since it can't find `System.Runtime`

For others I got no idea, please provide logs. But it's most likely the same issue.

**Comment by JingshanDu** [comment]
@lin-ycv Indeed! I just updated PT, and the problem is resolved. I had no idea PT changed .net target in the new release, so I did not expect this... Many thanks!

That being said, would it be possible to add a version checker to the updater to prevent this from happening in the future?

**Comment by lin-ycv** [comment]
The installer is intentionally dumb so that it doesn't trip antivirus false positives. 
Previously during development and testing, I did make a installer that does pre-installation checks and closed PT automatically, but it'd trip a quarter to half of the antivirus, so the installer was made dumb to lower the chance of triggering AV FP.
