### ISSUE TITLE
[BUG] Dispatcher processing has been suspended, but messages are still being processed.

### ISSUE THREAD

**Issue by daniel-richter** [lin-ycv/EverythingPowerToys#33]
**Describe the bug**
For certain search queries the error message box ("System.InvalidOperationException: Dispatcher processing has been suspended, but messages are still being processed.") appears. Depending on the query, there are a lot of error message windows that cause the whole system to freeze.

**To Reproduce**
I could track it down to the following:
- Having "Preview" option enabled (the error does not appear when it's disabled)
- Having a PDF file showing up in the search results

The strange thing is: I search (the first time) for "thesis.pdf" - the error message box appears; I close it. I search for "thesis.pdf" _aggain_ - the error message does _not_ appear, all search results are displayed correctly.

It feels like a error message is issued per PDF file in the search results. I am not sure if it is limited to PDF files only. I tried both Acrobat Preview Handler and Powertoys File Preview Handler for PDF.

**Screenshots**
![Unbenannt2](https://user-images.githubusercontent.com/12428377/204561345-49f52f16-2a83-49fc-b5ee-69971dba5212.PNG)
(The big black rectangle is the shadow of 1241 error message windows...)

**Logs (please upload or provide link to you log):**
```
2022-11-29 15:28:00.6366] [WARN] [C:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::207]
PluginManager.QueryForPlugin Window Walker. Query cost - 72 milliseconds

[2022-11-29 15:28:00.7650] [WARN] [C:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::207]
PluginManager.QueryForPlugin Program. Query cost - 62 milliseconds

[2022-11-29 15:28:01.0765] [WARN] [C:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::207]
PluginManager.QueryForPlugin Everything. Query cost - 311 milliseconds

[2022-11-29 15:28:01.3972] [FATAL]

## Exception

System.InvalidOperationException: Dispatcher processing has been suspended, but messages are still being processed.
   Source: WindowsBase
   TargetAssembly: WindowsBase, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
   TargetModule: WindowsBase.dll
   TargetSite: IntPtr WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

## Environment
* Command Line: "C:\Program Files\PowerToys\modules\launcher\PowerToys.PowerLauncher.dll" -powerToysPid 10828 --started-from-runner
* Timestamp: 11/29/2022 15:28:01
* Wox version: 0.64.1.0
* OS Version: Microsoft Windows NT 10.0.19045.0
* IntPtr Length: 8
* x64: True
* CLR Version: 6.0.11
* Installed .NET Framework: 
   * v4 Client 4.8.04084
   * v4 Full 4.8.04084
   * v4.0 Client 4.0.0.0
```

**Version (please provide the version of software you are using):**
- PowerToys.PowerLauncher, Version=0.64.1.0
- Community.PowerToys.Run.Plugin.Everything, Version=0.64.0.0
- Everything 1.4.1.1015
- Windows: Windows 10 Pro 22H2

**Comment by lin-ycv** [comment]
Is the pdf an online (onedrive/Google drive/ drop box) file?
Or a local file?

**Comment by daniel-richter** [comment]
It's a local file.

> I tried both Acrobat Preview Handler and Powertoys File Preview Handler for PDF.
Hm, I just realized that I didn't have PowerToy's _Icon Preview_ enabled, but just the _Preview Pane_. After enabling "PDF thumbnails" in PowerToys File Explorer extensions, the problem is gone.

But in general: The actual thumbnail generation is not the responsibility of the Everything plugin but of the Powertoys launcher, right?

**Comment by lin-ycv** [comment]
Related to https://github.com/microsoft/PowerToys/issues/18166

**Comment by jaimecbernardo** [comment]
For any users that are able to replicate this consistently, can you please update to 0.68.1 and disable thumbnail generation to verify if it fixes the issue? Please let us know on #18166!

![image](https://user-images.githubusercontent.com/26118718/223711215-7486c4ec-8486-41c7-8e3b-46a6a259a70c.png)
