### ISSUE TITLE
[Request] arm version

### ISSUE THREAD

**Issue by dXrayb** [lin-ycv/EverythingPowerToys#45]
**Describe the bug**
the plugin could not load well

-------------------------- Begin exception --------------------------
Message: Couldn't load assembly for Everything in C:\Program Files\PowerToys\modules\launcher\Plugins\Everything\Community.PowerToys.Run.Plugin.Everything.dll

Exception full name  : System.IO.FileLoadException
Exception message    : Could not load file or assembly 'Community.PowerToys.Run.Plugin.Everything, Version=0.66.0.0, Culture=neutral, PublicKeyToken=null'.
Exception stack trace:
   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr ptrNativeAssemblyBinder, UInt16* ilPath, UInt16* niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Wox.Plugin.PluginPair.CreatePluginInstance()
Exception source     : System.Private.CoreLib
Exception target site: Void <LoadFromPath>g____PInvoke|5_0(IntPtr, UInt16*, UInt16*, System.Runtime.CompilerServices.ObjectHandleOnStack)
Exception HResult    : -2146232799
-------------------------- End exception --------------------------

**Comment by lin-ycv** [comment]
@dXrayb sorry for the super delayed solution, finally got around to compiling an ARM64 version
can you test this and let me know if it works?
[EverythingARM64.zip](https://github.com/lin-ycv/EverythingPowerToys/files/11518203/EverythingARM64.zip)

**Comment by dXrayb** [comment]
> @dXrayb sorry for the super delayed solution, finally got around to compiling an ARM64 version can you test this and let me know if it works? [Everything.zip](https://github.com/lin-ycv/EverythingPowerToys/files/11518252/Everything.zip)

Thank you for support, but this plugin cannot load correctly, here is the log:
Version: 0.69.1.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True
Date: 2023/5/21 12:27:25
Exception:
System.BadImageFormatException: 试图加载格式不正确的程序。 (0x8007000B)
   at Community.PowerToys.Run.Plugin.Everything.Interop.NativeMethods.Everything_SetRegex(Boolean bEnable)
   at Community.PowerToys.Run.Plugin.Everything.Main.UpdateSettings(PowerLauncherPluginSettings settings)
   at Wox.Plugin.PluginPair.Update(PowerLauncherPluginSettings setting, IPublicAPI api)
   at PowerLauncher.SettingsReader.ReadSettings()
   at PowerLauncher.App.<>c__DisplayClass19_0.<OnStartup>b__0()
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action)
   at PowerLauncher.App.OnStartup(Object sender, StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Thank you for the help again.

**Comment by lin-ycv** [comment]
at least it's now able to start loading, but there seems to be some kind of incompatibility 
let me look into it more, not sure when I'll have a fix

**Comment by dXrayb** [comment]
I was using Everything X64 before, so I uninstall Everything first and then install Everything ARM64, after that I extracted plugin to the plugins folder, and used EverythingARM64_BETA.zip's dll to cover plugin folder's dll, at last I reboot the system and I got the same error:
Version: 0.70.0.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True
Date: 2023/5/25 15:41:49
Exception:
System.BadImageFormatException: 试图加载格式不正确的程序。 (0x8007000B)
   at Community.PowerToys.Run.Plugin.Everything.Interop.NativeMethods.Everything_SetRegex(Boolean bEnable)
   at Community.PowerToys.Run.Plugin.Everything.Main.UpdateSettings(PowerLauncherPluginSettings settings)
   at Wox.Plugin.PluginPair.Update(PowerLauncherPluginSettings setting, IPublicAPI api)
   at PowerLauncher.SettingsReader.ReadSettings()
   at PowerLauncher.App.<>c__DisplayClass19_0.<OnStartup>b__0()
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action)
   at PowerLauncher.App.OnStartup(Object sender, StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lin-ycv** [comment]
so this is a problem with Everything's SDK limitation, sorry, nothing I can do here.

**Comment by dXrayb** [comment]
Finally, it works, there is new updated dll, rename the file to Everything64.dll, it will works.
[Everything.ARM-SDK-update1.zip](https://github.com/lin-ycv/EverythingPowerToys/files/11573466/Everything.ARM-SDK-update1.zip)


> so this is a problem with Everything's SDK limitation, sorry, nothing I can do here.

**Comment by lin-ycv** [comment]
Could you let me know where you found this dll? I was sure I was using the newest DLL

**Comment by dXrayb** [comment]
I asked them from the author, and it is updated by VS2019.

**Comment by lin-ycv** [comment]
ARM support is officially added and will be part of the next release.
Users won't have to manually download a seperate dll.
