### ISSUE TITLE
NullReferenceException when disabling PowerToys Run

### ISSUE THREAD

**Issue by CEbbinghaus** [lin-ycv/EverythingPowerToys#5]
When turning off the PowerToys search toggle It crashes with a NullReferenceException that Originates from the Everything plugin

```err
Version: 0.56.2.0
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True
Date: 8/03/2022 2:40:20 PM
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Community.PowerToys.Run.Plugin.Everything.Main.Dispose(Boolean disposing)
   at Community.PowerToys.Run.Plugin.Everything.Main.Dispose()
   at PowerLauncher.Plugin.PluginManager.Dispose()
   at PowerLauncher.App.<>c__DisplayClass22_0.<Dispose>b__0()
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action)
   at PowerLauncher.App.Dispose(Boolean disposing)
   at PowerLauncher.App.Dispose()
   at PowerLauncher.App.ExitPowerToys(App app)
   at PowerLauncher.App.<>c__DisplayClass13_0.<Main>b__0()
   at System.Threading.Thread.StartCallback()
```

full log can be found [here](https://gist.github.com/CEbbinghaus/793fe51d41c58524b90fbba59d5403bf)

**Comment by lin-ycv** [comment]
OK, I think I know what the problem is, let me do some more testing, will try to get a fix out today.
