### ISSUE TITLE
[BUG] Error when click "open contains in folder"

### ISSUE THREAD

**Issue by Doradx** [lin-ycv/EverythingPowerToys#7]
**Describe the bug**
Sometimes, this plugin will report a bub and can't open the folder of the search result.

**To Reproduce**
1. search for a file of folder
2. click "open contains in folder"
3. just see the error

**Expected behavior**
none folder will be open, and an error dialog appeared, just as shown below.

**Screenshots**
![image](https://user-images.githubusercontent.com/23170065/158987425-c53de9fa-5d9d-4821-8325-968563618a60.png)
![image](https://user-images.githubusercontent.com/23170065/158987507-6ffeae6c-ed27-46a4-8fc6-51e163fc1c14.png)

**Logs (please upload or provide link to you log):**
 Logs can be generated by right clicking the taskbar icon > Report Bug
or be found at
%localappdata%\Microsoft\PowerToys\PowerToys Run\Logs
Version: 0.56.2.0
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True
Date: 2022/3/18 18:30:20
Exception:
System.MissingMethodException: Method not found: 'Boolean Wox.Infrastructure.Helper.OpenInShell(System.String, System.String, System.String, Boolean, Boolean)'.
   at Community.PowerToys.Run.Plugin.Everything.ContextMenuLoader.<>c__DisplayClass6_0.<CreateOpenContainingFolderResult>b__0(ActionContext _)
   at PowerLauncher.ViewModel.ResultViewModel.<>c__DisplayClass32_0.<LoadContextMenu>b__0(Object _)
   at MS.Internal.Command
[2022-03-18.txt](https://github.com/lin-ycv/EverythingPowerToys/files/8303753/2022-03-18.txt)
s.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Version (please provide the version of software you are using):**
 - PowerToy: 0.56.2.0
 - Everything: 1.4.1.1015
 - Windows: Windows 10 Pro 10.0.19044 Build 19044
[2022-03-18.txt](https://github.com/lin-ycv/EverythingPowerToys/files/8303763/2022-03-18.txt)

**Comment by lin-ycv** [comment]
I'm not sure why the it's unable to find the `Helper.OpenInShell` method, I've changed it to directly open the folder instead of relying on the method in Wox.

Please update to [Everything0562_R1.zip](https://github.com/lin-ycv/EverythingPowerToys/releases/download/v0.56.2/Everything0562_R1.zip), it should solve this issue.
