### ISSUE TITLE
[BUG] System.MissingMethodException: Method not found: Boolean Wox.Infrastructure.Helper.OpenInShell(...)

### ISSUE THREAD

**Issue by VAllens** [lin-ycv/EverythingPowerToys#9]
**Exception**
```console
Version: 0.56.2.0
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True
Date: 2022/3/28 9:10:30
Exception:
System.MissingMethodException: Method not found: 'Boolean Wox.Infrastructure.Helper.OpenInShell(System.String, System.String, System.String, Boolean, Boolean)'.
   at Community.PowerToys.Run.Plugin.Everything.ContextMenuLoader.<>c__DisplayClass6_0.<CreateOpenContainingFolderResult>b__0(ActionContext _)
   at PowerLauncher.ViewModel.ResultViewModel.<>c__DisplayClass32_0.<LoadContextMenu>b__0(Object _)
   at PowerLauncher.ViewModel.RelayCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**To Reproduce**
1. Press the `Atl + Space` key to open `PowerToys Run`.
2. Input `@Clash ext:exe`
3. Find the target item in the result list.
4. Click on the small folder icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/5094922/160311339-f7018d77-6e4e-45de-a0b9-56c82a87054b.png)

**Logs:**
[C:\Users\Administrator\AppData\Local\Microsoft\PowerToys\PowerToys Run\Logs\2022-03-28.txt](https://github.com/lin-ycv/EverythingPowerToys/files/8358983/2022-03-28.txt)

**Version (please provide the version of software you are using):**
 - PowerToy: v0.56.2
 - Everything: v1.4.1.105 (x64)
 - Windows: Windows 10 21H2 19044.1586

**Comment by lin-ycv** [comment]
this was fixed in R2, please upgrade to [Everything0562_R2.zip](https://github.com/lin-ycv/EverythingPowerToys/releases/download/v0.56.2/Everything0562_R2.zip)
https://github.com/lin-ycv/EverythingPowerToys/releases/tag/v0.56.2

**Comment by VAllens** [comment]
Good, it has worked correctly. 👍
